#!/bin/bash

PATH_TEMP_DIR="/home/fourcolor/Documents/ho_preditor/modem-utilities"
PATH_UTILS="/home/fourcolor/Documents/ho_preditor/modem-utilities"

function CHECK_temp_dir() {
if [ ! -d "$PATH_TEMP_DIR/temp" ] 
then
	mkdir "$PATH_TEMP_DIR/temp"
fi
}
function CHECK_my_SATA_dir() {
if [ ! -d "$PATH_TEMP_DIR/my_SATA" ] 
then
	mkdir "$PATH_TEMP_DIR/my_SATA"
fi
}
