Device:
  - qc00
  - qc02

SIDE_EFFECT_S: 0.4

Virt_Device:
  - device: dummy1
    shm_file: "/dev/shm/band_setting1"
    init_band: b1_b3_b7_b8
    side_effect_interfaces: [ul_veth1, dl_veth1]
  - device: dummy2
    shm_file: "/dev/shm/band_setting2"
    init_band: b1_b8
    side_effect_interfaces: [dl_veth2, ul_veth2]

band_candidate:
  - b1_b3
  - b1_b7
  - b1_b8
  - b3_b7
  - b3_b8
  - b7_b8

SLEEP_TIME: 3

PATH_TEMP_DIR: /home/fourcolor/Documents/ho_predictor/modem-utilities/temp
PATH_UTILS: /home/fourcolor/Documents/ho_predictor/modem-utilities

MODEL_PATH: "/home/fourcolor/Documents/ho_predictor/xgb_boost_scale_pos_weight_500_0.1_interval_3s_3s.json"

PREDICT_INTERVAL: 0.1
SAMPLE_INTERVAL: 0.1